version: '3'

services:
  express-api:
    build: ./app
    volumes:
      - "./app:/app:rw"
      - "/app/node_modules"
    restart: unless-stopped
    ports:
      - ${HTTP_PORT}:3000
    env_file:
      - .env
  
